run all tests and report failure at the end

diff --git a/.github/workflows/test-package.yaml b/.github/workflows/test-package.yaml
--- a/.github/workflows/test-package.yaml
+++ b/.github/workflows/test-package.yaml
@@ -37,12 +37,16 @@ jobs:
           poetry install --with dev,geo
       - name: ruff check
         run: poetry run ruff check --output-format=github .
+        continue-on-error: true
       - name: ruff import sorting check
         run: poetry run ruff check --select I --output-format=github .
+        continue-on-error: true
       - name: ruff lint
         run: poetry run ruff format --check .
+        continue-on-error: true
       - name: Review if metadata is updated
         uses: dorny/paths-filter@v3
+        continue-on-error: true
         id: changes
         with:
           filters: |
@@ -63,4 +67,10 @@ jobs:
       - name: Update CHANGELOG
         if: steps.changes.outputs.changelog == 'false'
         run: exit 1
+        continue-on-error: true
+      - name: Check for failures
+        if: failure()
+        run: |
+          echo "One or more steps have failed in the workflow." \ 
+          exit 1
         
